{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.europa.ec.eudi",
    "module": "eudi-lib-android-wallet-core",
    "version": "0.30.2-grnet.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-android-wallet-document-manager",
          "version": {
            "requires": "0.30.2-grnet.1"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-android-iso18013-data-transfer",
          "version": {
            "requires": "0.30.2-grnet.1"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-jvm-openid4vci-kt",
          "version": {
            "requires": "0.13.1"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz-android",
          "version": {
            "requires": "0.99.0"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "*"
            },
            {
              "group": "io.ktor",
              "module": "*"
            }
          ]
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-jvm-sdjwt-kt",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-kmp-statium-android",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "etsi-1196x2-consultation",
          "version": {
            "requires": "0.4.0-alpha.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "eudi-lib-android-wallet-core-0.30.2-grnet.1.aar",
          "url": "eudi-lib-android-wallet-core-0.30.2-grnet.1.aar",
          "size": 2492736,
          "sha512": "64ca54f90a99c146448e0ff5b867268a8408a43888b4526aada7c7d646608333295139673d15b31be7625892d468d1349fca9ea72350ee9271b6188c2dbe86e8",
          "sha256": "4270629b1ef2eff41b636c84f0974460d5bcc9a9df80fc11d7bab8c5e824f3a8",
          "sha1": "2a4699258a738920437887af1d1c29bda0358523",
          "md5": "bcafd303743741d8a508a6876bfd8ee0"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-android",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz-longfellow-android",
          "version": {
            "requires": "0.99.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.nimbusds",
          "module": "oauth2-oidc-sdk",
          "version": {
            "requires": "11.20.1"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-jvm-openid4vp-kt",
          "version": {
            "requires": "0.15.1"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "*"
            }
          ]
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "etsi-119602-consultation",
          "version": {
            "requires": "0.4.0-alpha.1"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.credentials.registry",
          "module": "registry-provider",
          "version": {
            "requires": "1.0.0-alpha04"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "co.nstant.in",
          "module": "cbor",
          "version": {
            "requires": "0.9"
          }
        },
        {
          "group": "com.upokecenter",
          "module": "cbor",
          "version": {
            "requires": "4.5.6"
          }
        },
        {
          "group": "com.augustcellars.cose",
          "module": "cose-java",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.3.0"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-android-wallet-document-manager",
          "version": {
            "requires": "0.30.2-grnet.1"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-android-iso18013-data-transfer",
          "version": {
            "requires": "0.30.2-grnet.1"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-jvm-openid4vci-kt",
          "version": {
            "requires": "0.13.1"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz-android",
          "version": {
            "requires": "0.99.0"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "*"
            },
            {
              "group": "io.ktor",
              "module": "*"
            }
          ]
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-jvm-sdjwt-kt",
          "version": {
            "requires": "0.20.0"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-kmp-statium-android",
          "version": {
            "requires": "0.5.1"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "etsi-1196x2-consultation",
          "version": {
            "requires": "0.4.0-alpha.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "eudi-lib-android-wallet-core-0.30.2-grnet.1.aar",
          "url": "eudi-lib-android-wallet-core-0.30.2-grnet.1.aar",
          "size": 2492736,
          "sha512": "64ca54f90a99c146448e0ff5b867268a8408a43888b4526aada7c7d646608333295139673d15b31be7625892d468d1349fca9ea72350ee9271b6188c2dbe86e8",
          "sha256": "4270629b1ef2eff41b636c84f0974460d5bcc9a9df80fc11d7bab8c5e824f3a8",
          "sha1": "2a4699258a738920437887af1d1c29bda0358523",
          "md5": "bcafd303743741d8a508a6876bfd8ee0"
        }
      ]
    },
    {
      "name": "releaseVariantMavenSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eudi-lib-android-wallet-core-0.30.2-grnet.1-sources.jar",
          "url": "eudi-lib-android-wallet-core-0.30.2-grnet.1-sources.jar",
          "size": 300340,
          "sha512": "2f8b65c26d34dce54ae4996beb544f6bc184868c560531c5c37ceb72cc1efd078d550cab8cbebe6176f9d0c9030402fff173c27e276fded0c251880185651ec4",
          "sha256": "2911ff38d4f512e3485a426746f3321ca3d76fbf9f2374dabcde0105d0a00249",
          "sha1": "2dabea486eb4cc944aa6df950765923333cceb58",
          "md5": "0fe36ec9188a27966292d6076104aab3"
        }
      ]
    },
    {
      "name": "releaseVariantMavenJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eudi-lib-android-wallet-core-0.30.2-grnet.1-javadoc.jar",
          "url": "eudi-lib-android-wallet-core-0.30.2-grnet.1-javadoc.jar",
          "size": 3521726,
          "sha512": "6c735224b4c2fb1a7f972413c965ecc47ac2c8c86861afd133cef01134d107e42332dd7194b64d0d7dabbe38c648cb8e9df53f50119318cb4df5a2ccbca93336",
          "sha256": "73962bd5853d72ca1c9c8c51a22bb6c1caee45a8b60ac8874c055af3545832bb",
          "sha1": "b223c96389bae2bff30679410121a98c7ecc8b45",
          "md5": "1c7f031359b6b9840e19446163c65599"
        }
      ]
    }
  ]
}
