{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.europa.ec.eudi",
    "module": "eudi-lib-android-iso18013-data-transfer",
    "version": "0.31.0-grnet.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantMavenApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "eudi-lib-android-iso18013-data-transfer-0.31.0-grnet.3.aar",
          "url": "eudi-lib-android-iso18013-data-transfer-0.31.0-grnet.3.aar",
          "size": 189251,
          "sha512": "a9e58903dcdd507ffd1e70ff43dce119e092ea43857cfd62243219a006f8efea145da18b4a494da0a17c382f0e0c08b0c2e62f1ec850adc085f2379cfd7fd666",
          "sha256": "d8072cb28dad673fb5655628574ed270014608c34c5eb9302fb6b16930195ba4",
          "sha1": "77d56bc07ced0981b191ce6e52b529c346314bb0",
          "md5": "6829b27ed9817d8ae397b4e3e09c770e"
        }
      ]
    },
    {
      "name": "releaseVariantMavenRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "eu.europa.ec.eudi",
          "module": "eudi-lib-android-wallet-document-manager",
          "version": {
            "requires": "0.31.0-grnet.3"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.multipaz",
          "module": "multipaz-android",
          "version": {
            "requires": "0.101.0"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "*"
            },
            {
              "group": "io.ktor",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.multipaz",
          "module": "multipaz-android-legacy",
          "version": {
            "requires": "0.101.0"
          },
          "excludes": [
            {
              "group": "org.bouncycastle",
              "module": "*"
            },
            {
              "group": "io.ktor",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-bytestring",
          "version": {
            "requires": "0.7.0"
          }
        },
        {
          "group": "com.google.zxing",
          "module": "core",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcprov-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.bouncycastle",
          "module": "bcpkix-jdk18on",
          "version": {
            "requires": "1.78.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.21"
          }
        }
      ],
      "files": [
        {
          "name": "eudi-lib-android-iso18013-data-transfer-0.31.0-grnet.3.aar",
          "url": "eudi-lib-android-iso18013-data-transfer-0.31.0-grnet.3.aar",
          "size": 189251,
          "sha512": "a9e58903dcdd507ffd1e70ff43dce119e092ea43857cfd62243219a006f8efea145da18b4a494da0a17c382f0e0c08b0c2e62f1ec850adc085f2379cfd7fd666",
          "sha256": "d8072cb28dad673fb5655628574ed270014608c34c5eb9302fb6b16930195ba4",
          "sha1": "77d56bc07ced0981b191ce6e52b529c346314bb0",
          "md5": "6829b27ed9817d8ae397b4e3e09c770e"
        }
      ]
    },
    {
      "name": "releaseVariantMavenSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eudi-lib-android-iso18013-data-transfer-0.31.0-grnet.3-sources.jar",
          "url": "eudi-lib-android-iso18013-data-transfer-0.31.0-grnet.3-sources.jar",
          "size": 65012,
          "sha512": "071ff07ca602a03005ca1a125b5f1db5bb90c3a082d0a1663b37bf39b622838f6c90fbdf4acc43882b626adb13ade3085b6e86820213810d873a26a793ceeed2",
          "sha256": "b7ce1970f713cd8a9f3074c4545eadcd61d29363fa024b1e8f58edb3c5c3fda4",
          "sha1": "f1c3f749b9e8aa7dfeb1126e0d28d9d4c9f32ab6",
          "md5": "748ea1682363bb9ab189437e5e5df7dd"
        }
      ]
    },
    {
      "name": "releaseVariantMavenJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "eudi-lib-android-iso18013-data-transfer-0.31.0-grnet.3-javadoc.jar",
          "url": "eudi-lib-android-iso18013-data-transfer-0.31.0-grnet.3-javadoc.jar",
          "size": 1178326,
          "sha512": "ddac3b8511190788a5360b1eba1e992ca01f887a22dd485c766f1676e0069645cca1dc3dfdce2d78599cc7559e06832f5ec477cdd8b88aaa5338efd413c3eb3e",
          "sha256": "8bb057f72990bb1c547ce8339f14286ac5acf37af298549d62cde8965c8e2994",
          "sha1": "ee88a6f648188675c1606612a4a0d2d59bef3dfd",
          "md5": "a15cbdbfe50a905589520aa38fd08b43"
        }
      ]
    }
  ]
}
